# Generated by Django 5.2.17 on 2026-09-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.JSONField(
                        help_text="List of [latitude, longitude] points along the road."
                    ),
                ),
                (
                    "distance_m",
                    models.PositiveIntegerField(
                        default=0, help_text="Road distance in metres."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="routes.stop",
                    ),
                ),
                (
                    "to_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="routes.stop",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_stop", "to_stop")},
            },
        ),
    ]
