# Generated by Django 5.2.17 on 2026-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wrong_pin_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
