# Generated by Django 5.2.17 on 2026-09-29 20:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pin_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile picture (DP), saved as a 400x400 JPEG.', upload_to=accounts.models.photo_path),
        ),
    ]
